import type { Locale } from '@/i18n/types'

const LOCALIZED: Record<Locale, string[]> = {
  id: [
    'Setiap hari tanpa kompulsi adalah investasi untuk dirimu yang jernih.',
    'Dorongan akan mereda dalam hitungan menit. Kamu hanya perlu menunggu.',
    'Pola lama bisa dipatahkan — satu keputusan kecil pada satu waktu.',
    'Fokusmu sedang pulih, sedikit demi sedikit.',
    'Kontrol yang kamu bangun hari ini akan jadi kekuatan besok.',
    'Dorongan bukan kamu. Itu hanya sinyal yang bisa dilewatkan.',
    'Tarik napas dalam 5 kali. Dorongan biasanya sudah lewat setelahnya.',
    'Cuci muka atau jalan sebentar. Perubahan fisik memutus siklus mental.',
    'Tanya pada dirimu: Hungry? Angry? Lonely? Tired? Biasanya jawabannya ada di sana.',
    'Kompulsi lahir dari pelarian. Temukan apa yang kamu hindari.',
    'Kamu tidak sedang kehilangan apa-apa. Kamu sedang mendapatkan kembali kendali.',
    'Orang yang kamu hormati juga berjuang dengan hal ini. Kamu tidak sendirian.',
    'Waktu yang kamu hemat hari ini untuk hal yang berarti, bukan hal yang mencuri.',
    'Setiap hari yang kamu menang membuatmu satu hari lebih kuat.',
    'Tubuh dan pikiranmu sudah cukup tanpa tambahan yang kosong.',
    'Bukan "aku harus tahan", tapi "aku memilih hal lain."',
    'Kamu bukan orang yang sedang mencoba berhenti. Kamu adalah orang yang memilih lebih.',
    'Identitasmu tidak ditentukan oleh dorongan. Tapi oleh responsmu.',
    'Pikiran kamu milikmu. Kamu bisa memilih apa yang kamu perhatikan.',
    'Kamu sudah sampai sejauh ini. Itu adalah bukti — bukan keberuntungan.',
  ],
  en: [
    'Every day without compulsion is an investment in the clearer you.',
    'The urge will ease in minutes. You just need to wait it out.',
    'Old patterns can be broken — one small decision at a time.',
    'Your focus is recovering, bit by bit.',
    'The control you build today becomes tomorrow\'s strength.',
    'The urge isn\'t you. It\'s just a signal you can let pass.',
    'Take 5 deep breaths. The urge has usually passed by then.',
    'Splash your face or walk a bit. Physical change breaks the mental loop.',
    'Ask yourself: Hungry? Angry? Lonely? Tired? The answer is usually there.',
    'Compulsion is born from escape. Find what you\'re avoiding.',
    'You\'re not losing anything. You\'re regaining control.',
    'People you respect struggle with this too. You\'re not alone.',
    'The time you save today goes to what matters, not to what steals.',
    'Every day you win makes you one day stronger.',
    'Your body and mind are enough without hollow additions.',
    'Not "I have to resist," but "I choose something else."',
    'You\'re not someone trying to quit. You are someone choosing more.',
    'Your identity isn\'t set by the urge. It\'s set by your response.',
    'Your mind is yours. You can choose what to pay attention to.',
    'You\'ve come this far. That\'s proof — not luck.',
  ],
}

export const pornQuotes = (locale: Locale): string[] => LOCALIZED[locale]
