import type { Locale } from '@/i18n/types'

const LOCALIZED: Record<Locale, string[]> = {
  id: [
    'Hatimu sedang membersihkan diri sekarang, setiap jam berlalu.',
    'Kadar alkohol darah turun drastis dalam 6 jam pertama.',
    'Setelah 2 minggu, tekanan darahmu sudah mulai turun.',
    'Kualitas tidur dalam (REM) pulih hanya setelah beberapa hari.',
    'Sel-sel hatimu mampu beregenerasi — beri mereka waktu.',
    'Risiko kanker mulut & tenggorokanmu menurun setiap tahun berlalu.',
    'Ingatan dan fokus membaik nyata dalam beberapa bulan.',
    'Dorongan ingin minum hanya berlangsung 10–20 menit. Kamu bisa.',
    'Tarik napas dalam. Minum segelas air dingin. Dorongan akan berlalu.',
    'Tubuhmu tidak butuh alkohol. Yang kamu rasakan hanya kebiasaan lama.',
    'Dorongan itu bukan kamu. Itu hanya sinyal otak yang bisa diabaikan.',
    'Jalan kaki 5 menit memutus siklus dorongan dengan cepat.',
    'Tanya pada dirimu: Hungry? Angry? Lonely? Tired?',
    'Hidup jernih lebih berharga dari sensasi sementara.',
    'Setiap hari tanpa alkohol adalah hadiah untuk dirimu di masa depan.',
    'Kamu tidak minum hari ini. Itu adalah kemenangan nyata.',
    'Orang yang peduli padamu bangga dengan pilihanmu.',
    'Uang yang kamu hemat nyata — dan terus bertambah.',
    'Pagi yang jernih adalah hadiah terindah untuk diri sendiri.',
    'Tidak ada kata terlambat untuk memilih hidup sadar.',
    'Bukan "aku tidak boleh minum", tapi "aku memilih untuk tidak."',
    'Kamu bukan peminum yang sedang mencoba berhenti. Kamu sudah bebas.',
    'Setiap godaan yang berhasil kamu lewati membuatmu semakin kuat.',
    'Besok pagi yang jernih adalah milikmu sepenuhnya.',
    'Kamu sudah membuktikannya. Hari demi hari, kamu berhasil.',
  ],
  en: [
    'Your liver is cleansing itself right now, with every passing hour.',
    'Blood alcohol levels drop sharply within the first 6 hours.',
    'After 2 weeks, your blood pressure has already started to fall.',
    'Deep (REM) sleep quality recovers after just a few days.',
    'Your liver cells can regenerate — give them time.',
    'Your risk of mouth & throat cancer drops every year that passes.',
    'Memory and focus improve noticeably within a few months.',
    'A drinking urge only lasts 10–20 minutes. You\'ve got this.',
    'Breathe deep. Drink a cold glass of water. The urge will pass.',
    'Your body doesn\'t need alcohol. What you feel is just old habit.',
    'The urge isn\'t you. It\'s just a brain signal you can ignore.',
    'A 5-minute walk breaks the urge cycle quickly.',
    'Ask yourself: Hungry? Angry? Lonely? Tired?',
    'Clear living is worth more than a fleeting sensation.',
    'Every alcohol-free day is a gift for your future self.',
    'You didn\'t drink today. That\'s a real victory.',
    'The people who care about you are proud of your choice.',
    'The money you\'re saving is real — and growing.',
    'A clear morning is the finest gift to yourself.',
    'It\'s never too late to choose a conscious life.',
    'Not "I can\'t drink," but "I choose not to."',
    'You\'re not a drinker trying to quit. You are already free.',
    'Every temptation you pass through makes you stronger.',
    'Tomorrow\'s clear morning is fully yours.',
    'You\'ve already proved it. Day by day, you\'re succeeding.',
  ],
}

export const alcoholQuotes = (locale: Locale): string[] => LOCALIZED[locale]
