import type { Locale } from '@/i18n/types'

const LOCALIZED: Record<Locale, string[]> = {
  id: [
    'Gula darahmu sedang menstabil sekarang, jam demi jam.',
    'Lidahmu sedang belajar lagi menikmati manis alami.',
    'Dalam 2 minggu, buah akan terasa lebih manis dari yang kamu ingat.',
    'Ngidam manis hanya berlangsung 10–20 menit. Kamu bisa melewatinya.',
    'Minum segelas air dulu — sering kali tubuhmu hanya haus, bukan ngidam.',
    'Energimu tidak lagi naik-turun seperti roller coaster. Itu kemenangan.',
    'Satu boba bisa melebihi batas gula sehari penuh. Hari ini kamu melewatkannya.',
    'Ngidam itu bukan kamu. Itu hanya sinyal otak yang bisa diabaikan.',
    'Jalan kaki 10 menit memutus siklus ngidam dengan cepat.',
    'Tanya pada dirimu: Haus? Lapar? Bosan? Lelah?',
    'Kulitmu berterima kasih — lebih sedikit gula, lebih sedikit glikasi.',
    'Setiap porsi manis yang kamu lewati adalah investasi untuk pankreasmu.',
    'Kamu tidak kehilangan rasa manis. Kamu menemukan manis yang sesungguhnya.',
    'Sarapan berprotein pagi ini = ngidam lebih ringan sore nanti.',
    'Uang boba yang kamu hemat nyata — dan terus bertambah.',
    'Tidur cukup malam ini adalah senjata anti-ngidam terbaikmu besok.',
    'Bukan "aku tidak boleh makan manis", tapi "aku memilih manis alami."',
    'Sore ini lelah? Itu ajakan jalan kaki, bukan ajakan boba.',
    'Kamu tidak minum manis hari ini. Itu kemenangan nyata.',
    'Fokusmu semakin tajam setiap hari tanpa lonjakan gula.',
    'Orang yang peduli padamu bangga dengan pilihanmu.',
    'Setiap ngidam yang berhasil kamu lewati membuatmu semakin kuat.',
    'Tubuhmu dirancang untuk manis dari buah — bukan dari botol.',
    'Kamu bukan pecandu manis yang sedang menahan diri. Kamu sudah bebas.',
    'Kamu sudah membuktikannya. Hari demi hari, kamu berhasil.',
  ],
  en: [
    'Your blood sugar is stabilizing right now, hour by hour.',
    'Your taste buds are relearning to enjoy natural sweetness.',
    'In 2 weeks, fruit will taste sweeter than you remember.',
    'A sugar craving only lasts 10–20 minutes. You can outlast it.',
    'Drink a glass of water first — often your body is just thirsty, not craving.',
    'Your energy no longer rides a roller coaster. That\'s a victory.',
    'One boba can exceed a whole day\'s sugar limit. Today you skipped it.',
    'The craving isn\'t you. It\'s just a brain signal you can ignore.',
    'A 10-minute walk breaks the craving cycle quickly.',
    'Ask yourself: Thirsty? Hungry? Bored? Tired?',
    'Your skin says thank you — less sugar, less glycation.',
    'Every sweet serving you skip is an investment in your pancreas.',
    'You\'re not losing sweetness. You\'re discovering the real thing.',
    'A protein breakfast this morning = lighter cravings this afternoon.',
    'The boba money you\'re saving is real — and growing.',
    'A good night\'s sleep is your best anti-craving weapon tomorrow.',
    'Not "I can\'t have sweets," but "I choose natural sweetness."',
    'Tired this afternoon? That\'s an invitation to walk, not to boba.',
    'You didn\'t drink sweet today. That\'s a real victory.',
    'Your focus sharpens every day without sugar spikes.',
    'The people who care about you are proud of your choice.',
    'Every craving you pass through makes you stronger.',
    'Your body was designed for sweetness from fruit — not from a bottle.',
    'You\'re not a sugar addict holding back. You are already free.',
    'You\'ve already proved it. Day by day, you\'re succeeding.',
  ],
}

export const sugarQuotes = (locale: Locale): string[] => LOCALIZED[locale]
