import type { Locale } from '@/i18n/types'

const LOCALIZED: Record<Locale, string[]> = {
  id: [
    'Paru-parumu sedang menyembuhkan diri sekarang, setiap detik.',
    'Setelah 20 menit berhenti, detak jantungmu sudah mulai normal.',
    'Karbon monoksida di darahmu turun drastis dalam 12 jam pertama.',
    'Setelah 2 minggu, peredaran darahmu membaik secara signifikan.',
    'Sel-sel rambut getar di paru-parumu sudah mulai berfungsi kembali.',
    'Risiko serangan jantungmu turun setiap hari yang berlalu.',
    'Indera penciumanmu perlahan kembali. Dunia terasa lebih hidup.',
    'Keinginan merokok hanya berlangsung 3 sampai 5 menit. Kamu bisa.',
    'Tarik napas dalam 4 hitungan. Tahan 4 detik. Buang pelan-pelan.',
    'Minum segelas air dingin sekarang. Keinginan itu akan berlalu.',
    'Tubuhmu tidak butuh rokok. Yang kamu rasakan hanya kebiasaan lama.',
    'Keinginan itu bukan kamu. Itu hanya sinyal otak yang bisa diabaikan.',
    'Jalan kaki 5 menit bisa memutus siklus keinginan itu.',
    'Kamu lebih kuat dari yang kamu kira.',
    'Setiap hari tanpa rokok adalah hadiah untuk dirimu di masa depan.',
    'Kamu tidak merokok hari ini. Itu adalah prestasi nyata.',
    'Orang-orang yang peduli padamu bangga dengan pilihanmu.',
    'Uang yang kamu hemat hari ini nyata dan terus bertambah.',
    'Kamu sedang menulis ulang cerita hidupmu, satu hari dalam satu waktu.',
    'Tidak ada kata terlambat untuk memilih kesehatan.',
    'Bukan "aku tidak boleh merokok", tapi "aku memilih untuk tidak."',
    'Kamu bukan perokok yang sedang mencoba berhenti. Kamu bebas.',
    'Setiap godaan yang berhasil kamu lewati membuatmu semakin kuat.',
    'Napas berikutnya adalah milikmu sepenuhnya.',
    'Kamu sudah membuktikannya. Kamu bisa melakukan ini.',
  ],
  en: [
    'Your lungs are healing right now, every second.',
    '20 minutes after quitting, your heart rate starts to normalize.',
    'Carbon monoxide in your blood drops sharply in the first 12 hours.',
    'After 2 weeks, your circulation improves significantly.',
    'The cilia in your lungs are already starting to work again.',
    'Your heart attack risk falls with every day that passes.',
    'Your sense of smell is slowly returning. The world feels more alive.',
    'A smoking craving only lasts 3 to 5 minutes. You\'ve got this.',
    'Breathe in for 4 counts. Hold for 4. Release slowly.',
    'Drink a cold glass of water right now. The urge will pass.',
    'Your body doesn\'t need cigarettes. What you feel is just old habit.',
    'The urge isn\'t you. It\'s just a brain signal you can ignore.',
    'A 5-minute walk can break the craving cycle.',
    'You are stronger than you think.',
    'Every smoke-free day is a gift for your future self.',
    'You didn\'t smoke today. That\'s a real achievement.',
    'The people who care about you are proud of your choice.',
    'The money you\'re saving today is real and growing.',
    'You\'re rewriting your own story, one day at a time.',
    'It\'s never too late to choose health.',
    'Not "I can\'t smoke," but "I choose not to."',
    'You\'re not a smoker trying to quit. You are free.',
    'Every temptation you pass through makes you stronger.',
    'Your next breath is fully yours.',
    'You\'ve already proved it. You can do this.',
  ],
}

export const smokingQuotes = (locale: Locale): string[] => LOCALIZED[locale]
